frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['matrix'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Displays Detail News.
     *
     * @return mixed
     */
    public function actionNoticiaDetalle(){
        return $this->render('noticia_detalle');
    }

    /**
     * Displays News.
     *
     * @return mixed
     */
    public function actionNoticias(){
        return $this->render('noticias');
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending email.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionMatrix(){
        $sql = "call mallpocket.matrix();";
        $db  = Yii::$app->db;
        $cmd = $db->createCommand($sql);
        $cmd->execute();
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
	
	/******* Controlador pagina Seccion ******/
    public function actionSeccion()
    {
        return $this->render('seccion');
    }

	
	

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for email provided.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password was saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }
}

frontend/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use frontend\assets\AppAsset;
use common\widgets\Alert;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>
<div class="container" style="margin-top: 10px;">
	<div class="pull-left">
		<div class="logo">
			<img class="img-responsive" src="../../frontend/img/LogoMallpocket.png" alt="">
		</div>		
	</div>
	<div class="pull-right">
		<div class="submenu">
			<ul>
				<li><a href="#">REVISTA<span>secciones</span></a></li>
				<li><a href="#">EDICIÓN No41<span>Noviembre 2016 <br> GOZADERA </span></a></li>
				<li><a href="#">EL PARCHE <span>las mentes detrás<br> de mp</span></a></li>
			</ul>
			<div class="socialicons">
				<p>siguenos en:</p>
				<a target="_blank" href="https://www.facebook.com/mimallpocket?fref=ts" title="Facebook">
					<img style="width: 30px;" src="../../frontend/img/ico_facebook.png" alt="Facebook">
				</a>
				<a target="_blank" href="https://twitter.com/mallpocket" title="Twitter">
					<img  style="width: 30px;" src="../../frontend/img/ico_tweet.png" alt="Twitter">
				</a>
				<a target="_blank" href="http://instagram.com/mallpocket/" title="Instagram">
					<img  style="width: 30px;"  src="../../frontend/img/ico_insta.png" alt="Instagram">
				</a>
			</div>
			<a href="#!">
				<div class="hamburguer">
					<img class="img-responsive" src="../../frontend/img/icno_menu.png" alt="">
				</div>
				<div class="closeM">
					<img class="img-responsive" src="../../frontend/img/close.png" alt="">
				</div>
			</a>
		</div>
	</div>
</div>
	<div class="container">
	<nav class="menu">
		<ul class="Nav_New">
			<li class="" id="visible"><a href="#">ACTUALIDAD</a>
			<ul id="hidden">			
				<li><a href="#">NOTICIAS</a></li>
				<li><a href="#">EVENTOS</a></li>
				<li><a href="#">VIRALES</a></li>
			</ul>
			</li>
			<li id="visible2"><a href="#">EDITORIAL</a>
			<ul id="hidden2">			
				<li><a href="#">CRONICAS</a></li>
				<li><a href="#">REPORTAJES</a></li>
				<li><a href="#">ENTREVISTAS</a></li>
				<li><a href="#">FICCIÓN</a></li>
			</ul>
			</li>
			<li id="visible3"><a href="#">GRÁFICO</a>
			<ul id="hidden3">			
				<li><a href="#">ILUSTRACIONES</a></li>
				<li><a href="#">FOTOGRAFÍAS</a></li>
				<li><a href="#">VIDEOS</a></li>
			</ul>
			</li>
			<li id="visible4"><a href="#">EDUCACIÓN</a>
			<ul id="hidden4">			
				<li><a href="#">BECAS</a></li>
				<li><a href="#">MODA UNIVERSITARIA</a></li>
				<li><a href="#">INSCRIPCIONES</a></li>
			</ul>
			</li>
			<li id="visible5"><a class="last" href="#">BLOGS</a>
			<!-- <ul id="hidden5">			
				<li><a href="#">BECAS</a></li>
				<li><a href="#">MODA UNIVERSITARIA</a></li>
				<li><a href="#">INSCRIPCIONES</a></li>
			</ul> -->
			</li>
		</ul>	
		</nav>
	</div>
	
	
	 <div class="container">
		<!----- Variable Contenido dinamico ----->
        <?= $content ?>
        <!----- /Variable Contenido dinamico ----->
    </div>
    
    
<?php $this->endBody() ?>
	
<footer class="footer">
    <div class="container">
	<p class="center">© Copyright 2017  /  Diseño Revista Editorial Bienestar S.A.S.  /  Todos los Derechos Reservados.
	Calle 106 N° 59 - 39 Oficina 101 / 3738326 </p>
    </div>
</footer> 
</body>
</html>

<script type="text/javascript">
$(".closeM").hide();
$(".hamburguer").click(function(){
	$(this).fadeOut('');
	$(".closeM").show('');
    $("nav.menu").slideDown();
});
	
$(".closeM").click(function(){
	$(this).fadeOut();
	$(".hamburguer").show('')
	$("nav.menu").slideUp();
});
</script>
<?php $this->endPage() ?>

frontend/views/layouts/main_x.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use frontend\assets\AppAsset;
use common\widgets\Alert;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'My Company',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    $menuItems = [
        ['label' => 'Home', 'url' => ['/site/index']],
        ['label' => 'About', 'url' => ['/site/about']],
        ['label' => 'Contact', 'url' => ['/site/contact']],
		['label' => 'seccion', 'url' => ['/site/seccion']],
    ];
    if (Yii::$app->user->isGuest) {
        $menuItems[] = ['label' => 'Signup', 'url' => ['/site/signup']];
        $menuItems[] = ['label' => 'Login', 'url' => ['/site/login']];
    } else {
        $menuItems[] = '<li>'
            . Html::beginForm(['/site/logout'], 'post')
            . Html::submitButton(
                'Logout (' . Yii::$app->user->identity->username . ')',
                ['class' => 'btn btn-link logout']
            )
            . Html::endForm()
            . '</li>';
    }
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $menuItems,
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>